<?php
const EMAIL_EMPTY_ERROR = "EMAIL IS REQUIRED";
const EMAIL_FORMAT_ERROR = 'EMAIL FORMAT INVALID';
const EMAIL_ALREADY_EXIST_ERROR = 'ACCOUNT CONNECTED TO GIVEN EMAIL ALREADY EXISTS';

const LOGIN_EMPTY_ERROR = "LOGIN IS REQUIRED";
const LOGIN_ALREADY_EXIST_ERROR = 'ACCOUNT CONNECTED TO GIVEN LOGIN ALREADY EXISTS';

const LOGGING_IN_ERROR = "GIVEN LOGIN AND PASSWORD COMBNATION DOES NOT EXIST";

const PASSWORD_REPETITION_ERROR = 'PASSWORD FIELDS DO NOT MATCH';
const PASSWORD_EMPTY_ERROR = 'PASSWORD IS REQUIRED';

const FILE_TOO_BIG_ERROR = "GIVEN FILE'S SIZE OVER ONE MB NOT ALLOVED ";
const FILE_TYPE_ERROR = 'ONLY .JPG AND .PNG EXTENSIONS ARE PERMITTED';

const AUTHOR_EMPTY_ERROR = "AUTHOR IS REQUIRED";

const TITLE_EMPTY_ERROR = "TITLE IS REQUIRED";

const WATERMARK_EMPTY_ERROR = "WATERMARK IS REQUIRED";

const REGISTER_SUCCESSFUL = "REGISTER SUCCESSFUL";
const LOGIN_SUCCESSFUL = "LOGIN SUCCESSFUL";
const LOGOUT_SUCCESSFUL = "LOGOUT SUCCESSFUL";
const UPLOAD_SUCCESSFUL = "UPLOAD SUCCESSFUL";

const PHOTOS_PATH = "photos";
const THUMBNAILS_PATH = "thumbnails";
const PHOTOS_WATERMARK_PATH = "photos_watermark";

const FONT = 'wigners_friend/Wigners.otf';

const THUMBNAILS_PER_PAGE = 4;
?>